name: CI

on:
    push:
        branches:
            - main
            - dev
    pull_request:
        branches:
            - "*"

env:
    FOUNDRY_PROFILE: ci
    SEPOLIA_RPC_URL: ${{ secrets.SEPOLIA_RPC }}

jobs:
    compile:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  submodules: recursive

            - name: Install Foundry
              uses: foundry-rs/foundry-toolchain@v1
              with:
                  version: nightly

            - name: Compile contracts
              id: compile_contracts
              run: forge build

            - name: Determine reaction
              if: always()
              id: reaction
              run: |
                  if [ "${{ steps.compile_contracts.outcome }}" = "success" ]; then
                    echo "reaction=rocket" >> $GITHUB_OUTPUT
                  else
                    echo "reaction=-1" >> $GITHUB_OUTPUT
                  fi

            - name: Remove existing reactions
              if: always()
              uses: actions/github-script@v6
              with:
                  github-token: ${{secrets.GITHUB_TOKEN}}
                  script: |
                      const { owner, repo, number } = context.issue;
                      const reactions = ['rocket', '-1'];
                      for (const reaction of reactions) {
                        try {
                          await github.rest.reactions.deleteForIssueComment({
                            owner,
                            repo,
                            comment_id: ${{ github.event.pull_request.number }},
                            reaction_id: reaction
                          });
                        } catch (error) {
                          console.log(`No ${reaction} reaction to remove or error removing it:`, error);
                        }
                      }

            - name: Comment PR
              if: always()
              uses: thollander/actions-comment-pull-request@v2
              continue-on-error: true
              with:
                  message: |
                      This is the **bot**.
                      Good work on the run
                      * Compiler: ${{ steps.compile_contracts.outcome == 'success' && '✅ Passed' || '❌ Failed' }}

                      _(execution **${{ github.run_id }}** / attempt **${{ github.run_attempt }}**)_
                  comment_tag: execution
                  reactions: ${{ steps.reaction.outputs.reaction }}
