name: CI

on:
    push:
        branches:
            - main
            - dev
    pull_request:
        branches:
            - "*"

env:
    FOUNDRY_PROFILE: ci
    SEPOLIA_RPC_URL: ${{ secrets.SEPOLIA_RPC }}

jobs:
    compile:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  submodules: recursive

            - name: Comment PR with execution number
              uses: thollander/actions-comment-pull-request@v2
              with:
                  message: |
                      _(execution **${{ github.run_id }}** / attempt **${{ github.run_attempt }}**)_
                  comment_tag: execution
